export default {
    data: [
        {
            school: 'ECNU',
            schoolFull: 'East China Normal University',
            college: 'College of Automation',
            logo: './school/ecnu.png',
            startDate: 1690383378873,
            graduationDate: undefined,
            degree: 'Bachelor',
            major: 'Electronic and Information Engineering',
            minor: 'Mathematics',
        },
        {
            school: 'SISU',
            schoolFull: 'Shanghai International Studies University',
            college: 'College of Liberal Arts',
            logo: './school/sisu.png',
            startDate: 1690383378873,
            graduationDate: 1690383378873,
            degree: 'Bachelor',
            major: 'English',
            minor: 'German',
        },
        {
            school: 'Tongji',
            schoolFull: 'Tongji University',
            college: 'College of Automotive Engineering',
            logo: './school/tongji.png',
            startDate: 1690383378873,
            graduationDate: 1690383378873,
            degree: 'Master',
            major: 'Automotive Design',
            minor: 'German',
        },
        {
            school: 'ECUST',
            schoolFull: 'East China University of Science and Technology',
            college: 'Sino-German College of Engineering',
            logo: './school/ecust.png',
            startDate: 1690383378873,
            graduationDate: 1690383378873,
            degree: 'Bachelor',
            major: 'Electrical Engineering and Automation',
            minor: 'German',
        },
    ],
}
