export default {
    title: 'Education',
    data: [
        {
            school: 'ECNU',
            schoolFull: 'East China Normal University',
            college: 'College of Automation',
            logo: './school/ecnu.png',
            startDate: '2021-01',
            graduationDate: undefined,
            degree: 'Bachelor',
            major: 'Electronic and Information Engineering',
            minor: 'Mathematics',
        },
        {
            school: 'SISU',
            schoolFull: 'Shanghai International Studies University',
            college: 'College of Liberal Arts',
            logo: './school/sisu.png',
            startDate: '2021-01',
            graduationDate: '2011-01',
            degree: 'Bachelor',
            major: 'English',
            minor: 'German',
        },
        {
            school: 'Tongji',
            schoolFull: 'Tongji University',
            college: 'College of Automotive Engineering',
            logo: './school/tongji.png',
            startDate: '2021-01',
            graduationDate: '2019-01',
            degree: 'Master',
            major: 'Automotive Design',
            minor: 'German',
        },
        {
            school: 'ECUST',
            schoolFull: 'East China University of Science and Technology',
            college: 'Sino-German College of Engineering',
            logo: './school/ecust.png',
            startDate: '2011-01',
            graduationDate: '2015-01',
            degree: 'Bachelor',
            major: 'Electrical Engineering and Automation',
            minor: 'German',
        },
    ],
    status: 0,
}
